name: Deploy React Gif App

on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm install

    # - name: Run the tests
    #   run: npm test

    - name: Build
      run: npm run build
      # env: 
      #   GH_PAT: ${{ secrets.GH_PAT }}
    - name: Deploy
      run: |
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'TefaSalcedo'
        user_email: 'stefa.dtbu@gmail.com'
        github_token: ${{ secrets.GH_PAT }}
        repository: ${{ github.repository }}
        GH_PAT: ${{ secrets.GH_PAT }}